# Generated by Django 2.2.16 on 2022-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(null=True, verbose_name='Tarix'),
        ),
    ]
